feature: shebang banner
formium/tsdx pull request #957
Opened 2021-01-18 14:15 UTC by huozhi

Use `rolloup.output.banner` to add shebang header into bundle. Resolves #338 

### Changes

* add `--bin` flag
* if `bin` is specified in package.json, output with shebang header

2021-01-18 14:24 UTC, huozhi commented
not sure why it's failed with node 12 + macOS, I'm currently using those as my local development env and installation + tests are passed locally.. 😂

2021-01-18 15:20 UTC, agilgur5 requested changes
Sorry but this approach does not work -- per  the comments #338 , the central problem is that the dev/prod entry, `index.js` was not written as a Rollup plugin and as such is written out-of-band without knowledge of shebangs.
Per the in-line comments below, `index.js`, which is the `bin` entry is not changed and the tests do not check for it properly

The correct approach, as I wrote there, is to convert that to a Rollup plugin and do shebang detection as well (no need for a `--bin` flag, though it could potentially be useful for newbies). Shebang detection was also partially removed at some point in time.

The plugin I'm working on does both of these things

2021-01-18 15:20 UTC, agilgur5 commented on test/e2e/tsdx-build-default.test.ts
> +    const output = execWithCache('node ../dist/index.js build');
To test shebangs, you'd want to exec `. ./dist/index.js` so that the shebang gets used

2021-01-18 15:20 UTC, agilgur5 commented on test/e2e/tsdx-build-default.test.ts
> +    const matched = grep(/#!\/usr\/bin\/env/, ['dist/build-default.*.js']);
This test isn't checking the most important file, `index.js`, which will not have it, which is why this PR will not work

2021-01-18 15:20 UTC, agilgur5 commented on src/types.ts
> +  // Is executive?
```suggestion
  // Is executable?
```
"executive" means something different

2021-01-18 15:20 UTC, agilgur5 commented on src/types.ts
> +  bin?: string | { [binary: string]: string };
should be `Boolean` like the docs and like `transpileOnly`

2021-01-18 15:21 UTC, closed without merging

2021-01-19 04:11 UTC, huozhi commented
got it, thanks for clarifying @agilgur5

2021-01-22 16:09 UTC, huozhi commented
@agilgur5 is that ok to use rollup-plugin-preserve-shebang to implement this feature? I can file another PR for it if the idea is acceptable for you

2021-01-22 17:22 UTC, agilgur5 commented
@huozhi unfortunately that will run into the same issue, it won't fix the `index.js` file. You might notice from the codebase/repo that TSDX actually used it at one point (before it was partially removed).

The optimal solution is a good bit more complicated as it requires a nuanced Rollup plugin and refactoring several internals. I have a branch that does it, but haven't gotten around to testing it or prioritizing it (mostly because of issues written in my current status)

2021-01-23 00:12 UTC, huozhi commented
understood, manually generating index.js of cjs bundle is definitely a blocker for that solution. thanks for your patient explanation! 🙏